### ISSUE TITLE
VPN Api not working

### ISSUE THREAD

**Issue by Raphael716** [ReinfyTeam/AntiVPN#11]
[21:22:18.083] (B[AsyncWorker#0 thread/CRITICAL]: (BErrorException: "Undefined array key 0" (EXCEPTION) in "/var/lib/pufferpanel/servers/513a24a6/plugins/AntiVPN-main/src/Tasks/ProxyCheckTask" at line 100
--- Stack trace ---
  #0 /var/lib/pufferpanel/servers/513a24a6/plugins/AntiVPN-main/src/Tasks/ProxyCheckTask(100): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[87] /var/lib/pufferpanel/servers/513a24a6/plugins/AntiVPN-main/src/Tasks/ProxyCheckT, int 100)
  #1 pmsrc/src/scheduler/AsyncTask(90): ReinfyTeam\AntiVPN\Tasks\ProxyCheckTask->onRun()
  #2 (): pocketmine\scheduler\AsyncTask->run()
--- End of exception information ---(B(B

**Comment by xRodzMC** [comment]
This is being to be tested. Not completed yet.

I'll release this version if this was done.
